# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ManyToManyField(related_name='all_likers', to='whisper.User')),
            ],
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('all_like', models.ManyToManyField(related_name='all_likes', to='whisper.Like')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='whisper.User')),
            ],
        ),
    ]
