# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0002_like_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='secret',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='secret',
            name='all_like',
        ),
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(related_name='all_likes', to='whisper.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
